/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MxaEKGtftF5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Card, CardContent } from "@/components/ui/card"
import Link from "next/link"

export function UserChannel() {
  return (
    <div>
      <div className="relative h-[300px] overflow-hidden w-full">
        <img
          src="/placeholder.svg"
          alt="Cover Image"
          width={1920}
          height={1080}
          className="h-full w-full object-cover"
        />
        <div className="absolute inset-0 bg-black/50 flex items-center justify-center">
          <div className="text-center text-white space-y-4">
            <h1 className="text-4xl font-bold">Vercel</h1>
            <p className="text-lg">@vercel</p>
            <p className="text-lg">Software company building tools for the modern web</p>
          </div>
        </div>
      </div>
      <div className="container mx-auto py-8 px-4 md:px-6">
        <div className="flex items-center gap-4">
          <Avatar className="h-16 w-16">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>YT</AvatarFallback>
          </Avatar>
          <div>
            <h2 className="text-2xl font-bold">Vercel</h2>
            <p className="text-sm text-muted-foreground">@vercel</p>
            <p className="text-sm text-muted-foreground">Software company building tools for the modern web</p>
          </div>
          <Button variant="outline" className="ml-auto">
            Subscribe
          </Button>
        </div>
        <Tabs defaultValue="home" className="w-full mt-8">
          <TabsList className="flex border-b">
            <TabsTrigger value="home">Home</TabsTrigger>
            <TabsTrigger value="videos">Videos</TabsTrigger>
            <TabsTrigger value="playlists">Playlists</TabsTrigger>
            <TabsTrigger value="live">Live</TabsTrigger>
          </TabsList>
          <TabsContent value="home">
            <div className="grid gap-6">
              <Carousel className="w-full">
                <CarouselContent>
                  <CarouselItem>
                    <div className="p-1">
                      <Card>
                        <CardContent className="flex aspect-square items-center justify-center p-6">
                          <div className="flex flex-col items-center gap-2">
                            <Avatar>
                              <AvatarImage src="/placeholder-user.jpg" />
                              <AvatarFallback>YT</AvatarFallback>
                            </Avatar>
                            <div className="text-sm font-medium">Vercel Tutorials</div>
                          </div>
                        </CardContent>
                      </Card>
                    </div>
                  </CarouselItem>
                  <CarouselItem>
                    <div className="p-1">
                      <Card>
                        <CardContent className="flex aspect-square items-center justify-center p-6">
                          <div className="flex flex-col items-center gap-2">
                            <Avatar>
                              <AvatarImage src="/placeholder-user.jpg" />
                              <AvatarFallback>YT</AvatarFallback>
                            </Avatar>
                            <div className="text-sm font-medium">Next.js 13 Tutorials</div>
                          </div>
                        </CardContent>
                      </Card>
                    </div>
                  </CarouselItem>
                  <CarouselItem>
                    <div className="p-1">
                      <Card>
                        <CardContent className="flex aspect-square items-center justify-center p-6">
                          <div className="flex flex-col items-center gap-2">
                            <Avatar>
                              <AvatarImage src="/placeholder-user.jpg" />
                              <AvatarFallback>YT</AvatarFallback>
                            </Avatar>
                            <div className="text-sm font-medium">Svelte Tutorials</div>
                          </div>
                        </CardContent>
                      </Card>
                    </div>
                  </CarouselItem>
                </CarouselContent>
                <CarouselPrevious />
                <CarouselNext />
              </Carousel>
            </div>
          </TabsContent>
          <TabsContent value="videos">
            <section>
              <h2 className="mb-4 text-xl font-bold">Latest Videos</h2>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View video</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Introducing v0: Generative UI</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">12:34</div>
                  </div>
                </div>
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View video</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Introducing the frontend cloud</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">8:45</div>
                  </div>
                </div>
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View video</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Using Vercel KV with Svelte</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">15:22</div>
                  </div>
                </div>
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View video</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Loading UI with Next.js 13</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">9:57</div>
                  </div>
                </div>
              </div>
            </section>
            <section className="mt-8">
              <h2 className="mb-4 text-xl font-bold">Popular Videos</h2>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View video</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Introducing v0: Generative UI</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">12:34</div>
                  </div>
                </div>
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View video</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Introducing the frontend cloud</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">8:45</div>
                  </div>
                </div>
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View video</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Using Vercel KV with Svelte</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">15:22</div>
                  </div>
                </div>
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View video</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Loading UI with Next.js 13</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">9:57</div>
                  </div>
                </div>
              </div>
            </section>
          </TabsContent>
          <TabsContent value="playlists">
            <section>
              <h2 className="mb-4 text-xl font-bold">Playlists</h2>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View playlist</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Vercel Tutorials</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">12 videos</div>
                  </div>
                </div>
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View playlist</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Next.js 13 Tutorials</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">8 videos</div>
                  </div>
                </div>
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View playlist</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Svelte Tutorials</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">15 videos</div>
                  </div>
                </div>
                <div className="relative flex flex-col gap-2">
                  <Link href="#" className="absolute inset-0" prefetch={false}>
                    <span className="sr-only">View playlist</span>
                  </Link>
                  <img
                    src="/placeholder.svg"
                    alt="Thumbnail"
                    width={320}
                    height={180}
                    className="aspect-video rounded-lg object-cover"
                  />
                  <div className="flex items-center justify-between">
                    <div className="line-clamp-2 text-sm font-medium">Vercel Deployment Tutorials</div>
                    <div className="rounded-md bg-black/50 px-2 py-1 text-xs text-white">9 videos</div>
                  </div>
                </div>
              </div>
            </section>
          </TabsContent>
          <TabsContent value="live">
            <div className="grid gap-4" />
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}
